<?php

$file_contents = "<?php
// Do not edit this file. It's generated by jetpack/tools/build-module-headings-translations.php
";

$jp_dir = dirname( dirname( __FILE__ ) ) . '/';
$files  = glob( "{$jp_dir}modules/*.php" );
$tags   = array(
	'Other' => array(),
);
foreach ( $files as $file ) {
	$absolute_path  = $file;
	$relative_path  = str_replace( $jp_dir, '', $file );
	$_file_contents = '';

	$file      = fopen( $absolute_path, 'r' );
	$file_data = fread( $file, 8192 );
	fclose( $file );

	// Make sure we catch CR-only line endings.
	$file_data = str_replace( "\r", "\n", $file_data );
	$all_headers = array(
		'name'                      => 'Module Name',
		'description'               => 'Module Description',
		'jumpstart_desc'            => 'Jumpstart Description',
		'sort'                      => 'Sort Order',
		'recommendation_order'      => 'Recommendation Order',
		'introduced'                => 'First Introduced',
		'changed'                   => 'Major Changes In',
		'deactivate'                => 'Deactivate',
		'free'                      => 'Free',
		'requires_connection'       => 'Requires Connection',
		'auto_activate'             => 'Auto Activate',
		'module_tags'               => 'Module Tags',
		'feature'                   => 'Feature',
		'additional_search_queries' => 'Additional Search Queries',
		'plan_classes'              => 'Plans',
	);
	foreach ( $all_headers as $field => $regex ) {
		if ( preg_match( '/^[ \t\/*#@]*' . preg_quote( $regex, '/' ) . ':(.*)$/mi', $file_data, $match ) && $match[1] ) {
			$string = trim( preg_replace( "/\s*(?:\*\/|\?>).*/", '', $match[1] ) );
			$string = addcslashes( $string, "''" );

			$_file_contents .= "\t\t\t\t'{$field}' => '{$string}'\n";

		}
	}



}
$file_contents .= "\t\t);
\t}";
$file_contents .= "\n\treturn \$modules[ \$key ];
}";


file_put_contents( "{$jp_dir}modules/module-registration.php", $file_contents );
